# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.15.1, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: export COCO_TRAVIS_TEST=1
    - run: npm install --ignore-scripts
    - run: npm install node-sass
    - run: npm install
    - run: export DISPLAY=:99.0
    - run: ./node_modules/karma/bin/karma start --browsers Firefox --single-run --reporters dots
    - run: npm run test-china
